all: train test
train: Train_TransE.cpp
	g++ Train_TransE.cpp -o Train_TransE -O2
test: Test_TransE.cpp
	g++ Test_TransE.cpp -o Test_TransE -O2
train_path: Train_TransE_path.cpp
	g++ Train_TransE_path.cpp -o Train_TransE_path -O2
train_RNN: Train_TransE_RNN.cpp
	g++ Train_TransE_RNN.cpp -o Train_TransE_RNN -O2
test_path: Test_TransE_path.cpp
	g++ Test_TransE_path.cpp -o Test_TransE_path -O2
