all: apcluster prepare generate
apcluster: apcluster.cpp
	g++ apcluster.cpp -o apcluster -O2
prepare: prepare.cpp
	g++ prepare.cpp -o prepare -O2
generate: generate.cpp
	g++ generate.cpp -o generate -O2
